### ISSUE TITLE
How to most efficiently sort entities of a query?

### ISSUE THREAD

**Issue by Lancelotbronner** [thygrrr/fennECS#28]
I have a console app setup as follows, what's the proper way to get these sorted by `Layer`?

I saw I could compile the query instead of getting a stream and sort the entities first but then I would have to manually fetch the components many times.

```csharp
public record struct ConsoleDrawable(
	char Character,
	byte Layer = 0x88,
	ConsoleColor Foreground = ConsoleColor.White,
	ConsoleColor Background = ConsoleColor.Black);

public readonly struct ConsoleRenderingSystem {
	private readonly Stream<Point, ConsoleDrawable> query;

	public ConsoleRenderingSystem(World world) {
		query = world
			.Query<Point, ConsoleDrawable>()
			.Stream();
	}

	public void Update() {
		query.For(Update);
	}

	private static void Update(ref Point position, ref ConsoleDrawable drawable) {
		Console.SetCursorPosition(position.X, position.Y);
		Console.BackgroundColor = drawable.Background;
		Console.ForegroundColor = drawable.Foreground;
		Console.Write(drawable.Character);
	}
}
```

**Comment by thygrrr** [comment]
Hey, sorry for taking long to reply here :)

1. Currently you will have to use a separate data structure for this ordering. You have to semantically ensure that structure is kept up to date, though. (easiest way is to do this with a component that keeps itself in a list, and that you manually dispose)

Future versions of fennecs plan to provide events as better means to keep external data structures such as spatial lookups updated. Probably 0.6.5-ish, though, so still a while away.

Note that this of course doesn't keep the actual memory access in memory contiguous.

2. Should you desire contiguous iteration, currently you can also group your entities using helper entities; but note that these aren't necessarily unique, and if you have too many of them (more than a few dozen), chances are you're fragmenting your archetypes a bit much.

Since this is part of the relation key, you also need to make sure only one of these gets added at the same time. (though the ability to do so can also be beneficial for other types of sorting/filtering, e.g. masks) But for Layers in an UI this might be good enough!

```cs
using var world = new World();

Entity[] groups = [world.Spawn(), world.Spawn(), world.Spawn(), world.Spawn()];

world.Spawn().Add("hello first", groups[0]);
world.Spawn().Add("hello last", groups[^1]);
world.Spawn().Add("hello second", groups[1]);
world.Spawn().Add("hello first, too", groups[0]);

foreach (var group in groups)
{
    world.Stream<string>(group).For((ref string message) => output.WriteLine(message));
}        
```

![image](https://github.com/user-attachments/assets/6cea8e48-878b-46fc-88aa-5e34dedea3bc)

This method will get better with fennecs 0.6.0 or 0.6.1 where Hash groups (i.e. you can group things by arbitrary values) become available. Relations have the advantage that they clean up themselves when the group entities are despawned.

3. Last but not least you can run an o(n²) sieve in your runner, depending on the number of entities this might be ok:
```cs
using var world = new World();

for (var i = 0; i < 200; i++)
{
    world.Spawn().Add(Random.Shared.Next() % 15); //15 hypothetical layers
}

for (var current = 0; current < 100; current++)
{
    world.Stream<int>().For(
        uniform: current,
        action: (int uniform, in Entity entity, ref int layer) =>
        {
            if (uniform == layer) output.WriteLine($"Hello from layer {layer}, {entity}");
            //pass in something more complex than an int in current to allow writing back
            //an early quit condition (i.e. "no entities in layer, this was the last one").
        });
}

```

**Comment by thygrrr** [comment]
Tagged as Documentation because this can go into Recipes. :)

**Comment by Lancelotbronner** [comment]
I went with tags for now since I only really ever have a handful of layers, thanks for your answer!
